listener 1883
allow_anonymous true

#save  broker data between containers
persistence true 
#were we should save it inside the container
persistence_location /mosquitto/data/ 

#print logs to the container output
log_dest stdout 